#GPU Data Center Demand Repsonse - Independent Study
#Laura Moreno - Cornell Tech
## Generated by Claude  (Anthropic), [Date]
# Model version: Claude 4.6 Sonnet



import numpy as np
from collections import defaultdict
import matplotlib.pyplot as plt


# ============================================================================
# STEP 1: DEFINE THE SYSTEM PARAMETERS
# ============================================================================

class GPUSystemParameters:

    
    def __init__(self):
       
        self.N_gpus = 2000  # Total number of GPUs

    
        self.G = 3
        n_per_class = self.N_gpus // self.G
        self.gpu_classes = [
            {'name': 'A16', 'memory': 16,  'n_gpus': n_per_class},
            {'name': 'A40', 'memory': 40,  'n_gpus': n_per_class},
            {'name': 'A80', 'memory': 80,  'n_gpus': self.N_gpus - 2 * n_per_class},
        ]

        # Precompute eligible GPU class indices for each memory requirement.
        # eligible_classes[mu] = [g_index, ...] sorted ascending (cheapest-fit first).
        all_memories = set(gc['memory'] for gc in self.gpu_classes)
        self.eligible_classes = {}
        for mu in all_memories:
            self.eligible_classes[mu] = [
                g for g, gc in enumerate(self.gpu_classes)
                if gc['memory'] >= mu
            ]

      
        # These are the *initial* counts at t=0.
        self.n_idle_per_class = [gc['n_gpus'] for gc in self.gpu_classes]

        # Freq Levels
        self.frequencies = {
            0: {'rate': 0.00, 'power': 50},   # Idle (leakage power only)
            1: {'rate': 0.25, 'power': 150},  # 25% speed
            2: {'rate': 0.50, 'power': 200},  # 50% speed  
            3: {'rate': 0.75, 'power': 250},  # 75% speed
            4: {'rate': 1.00, 'power': 300},  # 100% speed (max)
        }
        self.K = len(self.frequencies) 

        self.job_types = {
            'prefill': {
                'tau_r_mean': 2.0,   # F1 fix: was 10.0 (report1 §2)
                'tau_s_mean': 1.0,   # F1 fix: was 5.0
                'memory_req': 16,   # fits any GPU class
            },
            'decode': {
                'tau_r_mean': 30.0,
                'tau_s_mean': 20.0,
                'memory_req': 40,   # needs mid- or high-memory GPU
            },
            'fine_tuning': {
        
                'tau_r_mean': 15.0,
                'tau_s_mean': 10.0,
                'memory_req': 40,   # same as decode
            },
            'training': {
                'tau_r_mean': 40.0,
                'tau_s_mean': 25.0,
                'memory_req': 80,   # largest: only A80 class
            },
        }

        for jt in self.job_types.values():
            jt['tau_r_p'] = 1.0 / jt['tau_r_mean']
            jt['tau_s_p'] = 1.0 / jt['tau_s_mean']

        # Register every unique memory_req that appears in job_types so
        # eligible_classes covers them (they may not equal a class memory exactly).
        for jt in self.job_types.values():
            mu = jt['memory_req']
            if mu not in self.eligible_classes:
                self.eligible_classes[mu] = [
                    g for g, gc in enumerate(self.gpu_classes)
                    if gc['memory'] >= mu
                ]
       
        self.lambda_arrival = 5.0   # report1 §1: stable window λ < λ*≈18.4; was 60.0

        self.dt = 1.0  
        self.T_sim = 1000 
        
        # Power Target 
        # Power target — flat by default; set sinusoidal=True for time-varying
        self.sinusoidal          = True
        self.P_target_base       = 150_000     # W
        self.P_target_amplitude  =  30_000     # W  (±30 kW)
        self.P_target_period     =    200      # slots
        self.P_target            = self.P_target_base
        
     
        self.tau_max = 50  
        self.s_max = 20    

        self.lambda_smooth = 100 #smoothing penalty
        
    def get_rate(self, k):
        return self.frequencies[k]['rate']
    
    def get_power(self, k):
        return self.frequencies[k]['power']

    def class_memory(self, g):
        """Return GPU memory capacity (GB) for class g."""
        return self.gpu_classes[g]['memory']

    def class_n_gpus(self, g):
        """Return fleet size for class g."""
        return self.gpu_classes[g]['n_gpus']

    def eligible_classes_for(self, mu):
        """Return list of GPU class indices eligible for a job with memory_req µ."""
        return self.eligible_classes.get(mu, [])

    def p_target_at(self, t):
        """Return power target (W) at slot t."""
        if self.sinusoidal:
            return (self.P_target_base
                    + self.P_target_amplitude
                    * np.sin(2 * np.pi * t / self.P_target_period))
        return self.P_target_base


# ============================================================================
# STEP 2: DEFINE THE STATE SPACE
# ============================================================================

class PopulationState:
    """
    Tracks GPU population.

    Memory-class extension
    ----------------------
    * n_idle_per_class[g] : idle GPU count for class g
    * n_idle              : total idle GPUs (sum over classes, kept for compatibility)
    * waiting             : dict keyed by (tau, s, mu) -> float count
                            µ (memory_req) is stored so the admission step can
                            enforce the memory feasibility constraint m_g >= µ.
    * n                   : dict keyed by (tau, s) -> float count
                            (aggregate active busy count, class-agnostic for the LP)
    """

    def __init__(self, params):
        self.params = params

        self.n = defaultdict(float)

        # Idle GPU counts per class — initialised from params at t=0.
        self.n_idle_per_class = [float(params.class_n_gpus(g))
                                  for g in range(params.G)]

        # Waiting queue: keyed by (tau, s, mu) so admission can filter by memory.
        self.waiting = defaultdict(float)

    @property
    def n_idle(self):
        """Total idle GPUs across all classes."""
        return sum(self.n_idle_per_class)

    @n_idle.setter
    def n_idle(self, value):
        """Legacy setter — sets class-0 idle only. Prefer n_idle_per_class."""
        
        total = sum(self.n_idle_per_class)
        if total > 0:
            ratio = value / total
            self.n_idle_per_class = [v * ratio for v in self.n_idle_per_class]
        else:
            # distribute evenly
            per = value / self.params.G
            self.n_idle_per_class = [per] * self.params.G

    

    def get_count(self, tau, s, g):
        return self.n.get((tau, s, g), 0.0)

    def set_count(self, tau, s, g, count):
        if count > 0:
            self.n[(tau, s, g)] = count
        else:
            self.n.pop((tau, s, g), None)

    def get_all_states(self):
        """Returns list of (tau, s, g) tuples for occupied states."""
        return list(self.n.keys())

    def total_busy_gpus(self):
        return sum(self.n.values())

    def busy_gpus_per_class(self, G):
        """Returns list of busy GPU counts per class."""
        counts = [0.0] * G
        for (tau, s, g), n in self.n.items():
            counts[g] += n
        return counts

    def total_gpus(self):
        return self.n_idle + self.total_busy_gpus()

    def get_waiting_count(self, tau, s, mu=None):
        if mu is not None:
            return self.waiting.get((tau, s, mu), 0.0)
        # Legacy: sum over all µ for this (tau, s)
        return sum(v for (t, sl, m), v in self.waiting.items() if t == tau and sl == s)
    


# ============================================================================
# STEP 3: JOB ARRIVALS
# ============================================================================

class JobArrivalProcess:
    
    def __init__(self, params):
        self.params = params
        self.rng = np.random.default_rng(seed=42)
        self.job_type_names = list(params.job_types.keys())
        self.n_types        = len(self.job_type_names)
  
        
    def generate_arrivals(self):
    
        n_arrivals      = self.rng.poisson(self.params.lambda_arrival)
        weights         = np.ones(self.n_types) / self.n_types
        counts_per_type = self.rng.multinomial(n_arrivals, weights)

        arrivals = defaultdict(int)
        for jt_name, n_jt in zip(self.job_type_names, counts_per_type):
            jt = self.params.job_types[jt_name]
            mu = jt['memory_req']
            for _ in range(n_jt):
                tau_r = min(self.rng.geometric(jt['tau_r_p']), self.params.tau_max)
                tau_s = min(self.rng.geometric(jt['tau_s_p']), self.params.s_max)
                arrivals[(tau_r, tau_s, mu, jt_name)] += 1   # F3: type in key

        return arrivals
    
    
    
    def generate_arrivals_2(self):
       
       
        n_arrivals = self.rng.poisson(self.params.lambda_arrival)
        
        arrivals = defaultdict(int)
        
        for _ in range(n_arrivals):
        
            tau_r = self.rng.geometric(self.params.tau_r_p)
            tau_r = min(tau_r, self.params.tau_max)  # Cap at max
            
            
            tau_s = self.rng.geometric(self.params.tau_s_p)
            tau_s = min(tau_s, self.params.s_max)  # Cap at max
            
           
            arrivals[(tau_r, tau_s)] += 1
            
        return arrivals


# ============================================================================
# STEP 4: CONTROL POLICY (FREQUENCY ASSIGNMENT)
# ============================================================================

import numpy as np
from scipy.optimize import linprog
from collections import defaultdict

class LPControlPolicy:

    def __init__(self, params):
        self.params = params
        # Memory: stores u solution from the previous timestep.
        # Keys: (tau, s, k) -> float in [0, 1]
        # Used to penalize large changes in u between timesteps.
        self.u_prev = {}

    def compute_control_power(self, state, current_power):
  
        ts_counts = {}
        for (tau, s, g) in state.get_all_states():
            n = state.get_count(tau, s, g)
            if n > 0 and tau > 0:
                ts_counts[(tau, s)] = ts_counts.get((tau, s), 0.0) + n
        active_states = list(ts_counts.keys())
 
        if not active_states:
            return {}
        
        fixed_states = []
        free_states  = []
        for (tau, s) in active_states:
            if s == 0:
                fixed_states.append((tau, s))
            else:
                free_states.append((tau, s))
        
        u = {}

        #deterministic assignment because 100% of fixed states have to run at max frequency
        for (tau, s) in fixed_states:
            for k in range(self.params.K):
                if k == 4:
                    u[(tau, s, k)] = 1.0
                else:
                    u[(tau, s, k)] = 0.0
 
        if not free_states:
            # All states are deadline-critical; LP not needed
            return u

        P_idle = self.params.get_power(0)
        P_idle_total = P_idle * state.n_idle
 
        P_fixed = 0.0
        for (tau, s) in fixed_states:
            n = ts_counts.get((tau, s), 0.0)
            P_fixed = P_fixed + n * self.params.get_power(4)  # forced at k=4
 
        #Subtract P_idle ad P_fixed_states from my P_target
        P_busy_target = max(0.0, self.params.P_target - P_idle_total - P_fixed)

        ##---------- LP variables----------------------------
        # Variable layout:
        #   [u_vars (n_free * n_K)] | [e (1)] | [d_vars (n_free * n_K)]
        #
        # u[i,k]  : fraction of state i running at frequency k  (n_free * n_K vars)
        # e       : absolute power tracking error               (1 var)
        # d[i,k]  : |u[i,k] - u_prev[i,k]|, the change penalty (n_free * n_K vars)

        K_busy = [1, 2, 3, 4]  
        n_free   = len(free_states)
        n_K      = len(K_busy)
        n_vars_u = n_free * n_K
        idx_e    = n_vars_u          # Index of the slack variable e
        idx_d    = n_vars_u + 1      # Start index of d variables
        n_vars   = n_vars_u + 1 + n_vars_u  # u + e + d

    
        var_index = {}
        for i in range(n_free):
            tau, s = free_states[i]
            for j in range(n_K):
                k = K_busy[j]
                var_index[(tau, s, k)] = i * n_K + j

        # ----------------------------------------------------------------
        # OBJECTIVE: minimize  e  +  lambda * sum(d[i,k])
        #
        # The lambda_smooth weight trades off:
        #   - small lambda -> tracks power well, may be jumpy
        #   - large lambda -> smoother u, may miss power target slightly
        # ----------------------------------------------------------------
        lam = self.params.lambda_smooth
        c = np.zeros(n_vars)
        c[idx_e] = 1.0                          # penalize power error
        for col in range(n_vars_u):
            c[idx_d + col] = lam                # penalize u changes


        # p_row[col]: power contributed per unit of u variable col
        p_row = np.zeros(n_vars_u)
        for i in range(n_free):
            tau, s = free_states[i]
            n = ts_counts.get((tau, s), 0.0)  # aggregated across classes
            for j in range(n_K):
                k   = K_busy[j]
                P_k = self.params.get_power(k)
                col = i * n_K + j
                p_row[col] = n * P_k

        # ----------------------------------------------------------------
        # INEQUALITY CONSTRAINTS  A_ub @ x <= b_ub
        #
        # Power tracking (rows 0-1):
        #   Row 0:  p_row @ u  - e           <=  P_busy_target
        #   Row 1: -p_row @ u  - e           <= -P_busy_target
        #
        # Smoothing / linearized absolute value (rows 2 to 2+2*n_vars_u-1):
        #   For each variable col in [0, n_vars_u):
        #     u[col] - u_prev[col]  - d[col] <= 0   =>  d >= u - u_prev
        #    -u[col] + u_prev[col]  - d[col] <= 0   =>  d >= -(u - u_prev)
        # ----------------------------------------------------------------
        # Build sparse constraint matrices (F5-friendly: avoids dense OOM at large state counts)
        from scipy.sparse import lil_matrix, csc_matrix as _csc
        n_ineq = 2 + 2 * n_vars_u
        A_ub_sp = lil_matrix((n_ineq, n_vars))
        b_ub    = np.zeros(n_ineq)

        for col in range(n_vars_u):
            A_ub_sp[0, col] =  p_row[col]
            A_ub_sp[1, col] = -p_row[col]
        A_ub_sp[0, idx_e] = -1.0;  b_ub[0] =  P_busy_target
        A_ub_sp[1, idx_e] = -1.0;  b_ub[1] = -P_busy_target

        for col in range(n_vars_u):
            i_state = col // n_K
            j_freq  = col  % n_K
            tau, s  = free_states[i_state]
            k       = K_busy[j_freq]
            u_p     = self.u_prev.get((tau, s, k), 0.5)
            row_pos = 2 + 2 * col
            row_neg = 3 + 2 * col
            A_ub_sp[row_pos, col]       =  1.0;  A_ub_sp[row_pos, idx_d + col] = -1.0;  b_ub[row_pos] =  u_p
            A_ub_sp[row_neg, col]       = -1.0;  A_ub_sp[row_neg, idx_d + col] = -1.0;  b_ub[row_neg] = -u_p

        A_eq_sp = lil_matrix((n_free, n_vars))
        b_eq    = np.ones(n_free)
        for i in range(n_free):
            for j in range(n_K):
                A_eq_sp[i, i * n_K + j] = 1.0

        bounds = ([(0.0, 1.0)] * n_vars_u) + [(0.0, None)] + ([(0.0, None)] * n_vars_u)

        result = linprog(
            c,
            A_ub=_csc(A_ub_sp), b_ub=b_ub,
            A_eq=_csc(A_eq_sp), b_eq=b_eq,
            bounds=bounds,
            method='highs',
            options={'disp': False}
        )
 
       
        if result.success:
            x = result.x
            for i in range(n_free):
                tau, s = free_states[i]
                u[(tau, s, 0)] = 0.0  # k=0 not available to busy GPUs
                for j in range(n_K):
                    k   = K_busy[j]
                    col = var_index[(tau, s, k)]
                    u_val = float(x[col])
                    # Clip for numerical safety (solver may return tiny negatives)
                    if u_val < 0.0:
                        u_val = 0.0
                    if u_val > 1.0:
                        u_val = 1.0
                    u[(tau, s, k)] = u_val

            # --- Store solution as u_prev for next timestep ---
            self.u_prev = {key: val for key, val in u.items()}

        else:
    
            print(f"  [LP] Warning: solver status={result.status}, "
                  f"message='{result.message}'. Using uniform fallback.")
            for i in range(n_free):
                tau, s = free_states[i]
                u[(tau, s, 0)] = 0.0
                for j in range(n_K):
                    k = K_busy[j]
                    u[(tau, s, k)] = 1.0 / n_K

            # Store fallback as u_prev too
            self.u_prev = {key: val for key, val in u.items()}
 
        return u
 

# ============================================================================
# STEP 5: STATE TRANSITIONS (POPULATION DYNAMICS)
# ============================================================================

class PopulationDynamics:
   #holds equation 10 of technical note
    
    def __init__(self, params):
        self.params = params
        # ── Job tracking counters ─────────────────────────────────────────
        self.total_jobs_missed    = 0.0
        self.missed_by_mu         = defaultdict(float)   # mu -> count
        self.missed_by_type       = defaultdict(float)   # F3: job_type -> count
        self.total_jobs_admitted  = 0.0                  # F5: conservation check 2
        self.total_jobs_completed = 0.0                  # F5: conservation check 3
        
    def evolve(self, state, control, arrivals, current_power):

        from collections import defaultdict
    
        new_state = PopulationState(self.params)
        new_state.waiting = defaultdict(float, state.waiting)
        # Copy per-class idle counts from previous state
        new_state.n_idle_per_class = list(state.n_idle_per_class)

        # ── 1. Enqueue new arrivals (tau, s, mu, job_type) ───────────────
        for (tau, s, mu, jtype), count in arrivals.items():
            new_state.waiting[(tau, s, mu, jtype)] += count

        # ── 2. Estimate power freed by finishing jobs ──────────────────────
        predicted_power_loss = 0.0

        for (tau, s, g) in state.get_all_states():
            n_current = state.get_count(tau, s, g)
            if n_current == 0:
                continue
            for k in range(self.params.K):
                u_k = control.get((tau, s, k), 0.0)
                if u_k == 0:
                    continue
                n_at_k = u_k * n_current
                r_k    = self.params.get_rate(k)
                tau_next = tau - r_k
                if tau_next <= 0:
                    P_k   = self.params.get_power(k)
                    P_idle = self.params.get_power(0)
                    predicted_power_loss += n_at_k * (P_k - P_idle)

        power_gap        = self.params.P_target - current_power
        adjusted_headroom = power_gap + predicted_power_loss

        avg_power_per_new_job = self._estimate_avg_power_for_new_jobs(state, control)
        if avg_power_per_new_job > 0:
            max_new_gpus = max(0.0, adjusted_headroom / avg_power_per_new_job)
        else:
            max_new_gpus = 0.0
        max_new_gpus = min(max_new_gpus, 500)

        # ── 3. Admit jobs — MEMORY FEASIBILITY CONSTRAINT ─────────────────
        #
        # Technical note §5.1, eq.(11): a job with memory requirement µ can
        # only be assigned to an idle GPU of class g where  m_g >= µ.
        #
        # Policy: cheapest-fit — within feasible classes, prefer the lowest-
        # memory class that still satisfies the constraint (smallest m_g >= µ).
        # This preserves high-memory GPUs for jobs that actually need them.
        #
        # Waiting jobs are sorted by urgency (ascending slack ratio s/(τ+s)):
        # most urgent jobs are admitted first when headroom is limited.

        gpus_assigned = 0.0

        # Sort waiting jobs: most urgent first (lowest slack ratio)
        def urgency_key(key):
            tau, s, mu, jtype = key   # F3: 4-tuple
            return tau + s            # EDF: ascending deadline

        waiting_keys = sorted(
            [k for k, v in new_state.waiting.items() if v > 0],
            key=urgency_key
        )

        for (tau, s, mu, jtype) in waiting_keys:
            if gpus_assigned >= max_new_gpus:
                break

            waiting_count = new_state.waiting.get((tau, s, mu, jtype), 0.0)
            if waiting_count <= 0:
                continue
            eligible = self.params.eligible_classes_for(mu)

            # Try to admit across eligible classes (cheapest-fit first)
            for g in eligible:
                if gpus_assigned >= max_new_gpus:
                    break
                if new_state.n_idle_per_class[g] <= 0:
                    continue

                remaining_count = new_state.waiting.get((tau, s, mu, jtype), 0.0)
                if remaining_count <= 0:
                    break

                can_assign = min(
                    remaining_count,
                    new_state.n_idle_per_class[g],
                    max_new_gpus - gpus_assigned,
                )

                new_state.waiting[(tau, s, mu, jtype)] -= can_assign
                if new_state.waiting[(tau, s, mu, jtype)] <= 0:
                    new_state.waiting.pop((tau, s, mu, jtype), None)

                # Store with class g in key so completions return to correct class
                new_state.set_count(tau, s, g,
                    new_state.get_count(tau, s, g) + can_assign)
                new_state.n_idle_per_class[g] -= can_assign
                gpus_assigned += can_assign
                self.total_jobs_admitted += can_assign   # F5 check 2

        # ── 4. Tick slack for remaining waiting jobs ───────────────────────
        waiting_next = defaultdict(float)
        for (tau, s, mu, jtype), count in new_state.waiting.items():
            if count <= 0:
                continue
            s_next = s - 1
            if s_next < 0:
                # F3: record miss by both mu and job type
                self.total_jobs_missed    += count
                self.missed_by_mu[mu]     += count
                self.missed_by_type[jtype] += count   # F3 new
            else:
                waiting_next[(tau, s_next, mu, jtype)] += count
        new_state.waiting = waiting_next

        # ── 5. Advance active jobs ─────────────────────────────────────────
        for (tau, s, g) in state.get_all_states():
            n_current = state.get_count(tau, s, g)
            if n_current == 0:
                continue
            for k in range(self.params.K):
                u_k = control.get((tau, s, k), 0.0)
                if u_k == 0:
                    continue
                n_at_k   = u_k * n_current
                r_k      = self.params.get_rate(k)
                tau_next = tau - r_k
                s_next   = s   - (1 - r_k)

                if tau_next <= 0:
                    # Job finished — return GPUs to the exact class g they came from
                    freed = n_at_k
                    self.total_jobs_completed += freed          # F5 check 3
                    new_state.n_idle_per_class[g] += freed      # correct class only
                else:
                    tau_next = round(tau_next * 4) / 4
                    s_next   = max(0, round(s_next * 4) / 4)
                    new_state.set_count(tau_next, s_next, g,
                                        new_state.get_count(tau_next, s_next, g) + n_at_k)

        return new_state

    def _estimate_avg_power_for_new_jobs(self, state, control):
        """
        Estimate average power consumption for newly admitted jobs.
    
        Strategy: Look at current control policy to see what frequency
        new jobs with typical slack would run at.
        """
        # Sample some typical new job states
        typical_states = [
        (10, 5),   # Medium job, medium slack
        (5, 2),    # Short job, low slack
        (20, 10),  # Long job, high slack
        ]
    
        total_power = 0
        count = 0
    
        for (tau, s) in typical_states:
            # What frequency would control assign to this state?
            for k in range(self.params.K):
                u_k = control.get((tau, s, k), 0.0)
                if u_k > 0:
                    P_k = self.params.get_power(k)
                    total_power += u_k * P_k
                    count += u_k
    
        if count > 0:
            return total_power / count
        else:
            # Fallback: assume 50% frequency
            return 200.0



# ============================================================================
# STEP 6: POWER CALCULATION
# ============================================================================

class PowerCalculator:
    """
    This implements Equation 16 from the technical note.
    """
    
    def __init__(self, params):
        self.params = params
        
    def compute_power(self, state, control):
        """
        Calculate total power consumption.
        
        P_total = P_idle * n_idle + ∑_{tau,s} ∑_k u[tau,s,k] * n[tau,s] * P_k
        
        Returns:
            power in Watts
        """
        # Idle GPU power
        P_idle = self.params.get_power(0)
        power_from_idle = P_idle * state.n_idle
        
        # Busy GPU power
        power_from_busy = 0.0

        for (tau, s, g) in state.get_all_states():
            n = state.get_count(tau, s, g)

            if n == 0:
                continue

            for k in range(self.params.K):
                u_k = control.get((tau, s, k), 0.0)
                
                if u_k == 0:
                    continue
                
                P_k = self.params.get_power(k)
                power_from_busy += u_k * n * P_k
        
        return power_from_idle + power_from_busy


# ============================================================================
# STEP 7: THE SIMULATOR (PUTS IT ALL TOGETHER)
# ============================================================================

class GPUSimulator:
    """
    Main simulation loop.
    Coordinates all the pieces: arrivals, control, dynamics, power.
    """
    
    def __init__(self, params):
        self.params = params
        
        # Initialize components
        self.arrivals = JobArrivalProcess(params)
        self.policy = LPControlPolicy(params)
        self.dynamics = PopulationDynamics(params)
        self.power_calc = PowerCalculator(params)
        
        # Initial state
        self.state = PopulationState(params)
        
        # Job arrival/miss counters
        self.total_jobs_arrived = 0
        # F5: conservation violation counters
        self.conservation_violations = 0

        # History (for plotting)
        self.history = {
            'time': [],
            'power': [],
            'p_target': [],
            'n_idle': [],
            'n_busy': [],
            'queue_size': [],
            'waiting_queue': [],
            # per-class idle counts (list of G-length lists, one per timestep)
            'n_idle_per_class': [],
        }
        
    def run(self):
        """Run the simulation for T time steps"""
        
        print("Starting simulation...")
        print(f"Target power: {self.params.P_target/1000:.1f} kW")
        print(f"GPU memory classes:")
        for g, gc in enumerate(self.params.gpu_classes):
            print(f"  Class {g} ({gc['name']}, {gc['memory']} GB): {gc['n_gpus']} GPUs")
        print(f"Job types and memory requirements:")
        for jt_name, jt in self.params.job_types.items():
            eligible = [self.params.gpu_classes[g]['name']
                        for g in self.params.eligible_classes_for(jt['memory_req'])]
            print(f"  {jt_name}: µ={jt['memory_req']} GB → eligible: {eligible}")
        print()

        power_prev = self.params.get_power(0) * self.params.N_gpus
        
        for t in range(self.params.T_sim):
            arrivals_t = self.arrivals.generate_arrivals()
            self.params.P_target = self.params.p_target_at(t)
            self.total_jobs_arrived += sum(arrivals_t.values())
            
            control_t = self.policy.compute_control_power(self.state, power_prev)

            self.state = self.dynamics.evolve(self.state, control_t, arrivals_t, power_prev)

            # ── F5: Conservation checks (every slot) ──────────────────────
            # Check 1: GPU conservation per class
            #   n_idle_g + busy_g (estimated as proportional share) ≈ N_g
            #   We use total idle + total busy = N_gpus as the aggregate check
            # Check per-class conservation: idle_g + busy_g = N_g
            busy_per_class = self.state.busy_gpus_per_class(self.params.G)
            for g in range(self.params.G):
                N_g         = self.params.class_n_gpus(g)
                idle_g      = self.state.n_idle_per_class[g]
                busy_g      = busy_per_class[g]
                discrepancy = abs(idle_g + busy_g - N_g)
                if discrepancy > 1.0:
                    self.conservation_violations += 1
                    if self.conservation_violations <= 5:
                        gc_name = self.params.gpu_classes[g]['name']
                        print(f"  [F5 VIOLATION t={t}] GPU conservation class {gc_name}: "
                              f"idle({idle_g:.1f}) + busy({busy_g:.1f}) = "
                              f"{idle_g+busy_g:.1f} != N_g({N_g})")

            # Check 2: Arrival accounting (cumulative)
            #   total_arrived >= total_admitted + total_missed + currently_queued
            currently_queued = sum(self.state.waiting.values())
            accounted = (self.dynamics.total_jobs_admitted
                         + self.dynamics.total_jobs_missed
                         + currently_queued)
            arrival_discrepancy = abs(self.total_jobs_arrived - accounted)
            if arrival_discrepancy > 1.0:
                self.conservation_violations += 1
                if self.conservation_violations <= 5:
                    print(f"  [F5 VIOLATION t={t}] Arrival accounting: "
                          f"arrived({self.total_jobs_arrived:.0f}) != "
                          f"admitted({self.dynamics.total_jobs_admitted:.0f}) + "
                          f"missed({self.dynamics.total_jobs_missed:.0f}) + "
                          f"queued({currently_queued:.0f}) = {accounted:.0f}")

            # Check 3: Job population (cumulative)
            #   total_arrived = total_completed + total_missed + currently_in_system
            in_system = self.state.total_busy_gpus() + currently_queued
            population = (self.dynamics.total_jobs_completed
                          + self.dynamics.total_jobs_missed
                          + in_system)
            pop_discrepancy = abs(self.total_jobs_arrived - population)
            if pop_discrepancy > 1.0:
                self.conservation_violations += 1
                if self.conservation_violations <= 5:
                    print(f"  [F5 VIOLATION t={t}] Population: "
                          f"arrived({self.total_jobs_arrived:.0f}) != "
                          f"completed({self.dynamics.total_jobs_completed:.0f}) + "
                          f"missed({self.dynamics.total_jobs_missed:.0f}) + "
                          f"in_system({in_system:.0f}) = {population:.0f}")
            # ── end F5 checks ─────────────────────────────────────────────

            power_t = self.power_calc.compute_power(self.state, control_t)
            power_prev = power_t
            
            self.history['time'].append(t)
            self.history['power'].append(power_t)
            self.history['p_target'].append(self.params.P_target)
            self.history['n_idle'].append(self.state.n_idle)
            self.history['n_busy'].append(self.state.total_busy_gpus())
            self.history['queue_size'].append(len(self.state.get_all_states()))
            waiting_total = sum(self.state.waiting.values())
            self.history['waiting_queue'].append(waiting_total)
            self.history['n_idle_per_class'].append(
                list(self.state.n_idle_per_class))
            
            if t % 10 == 0:
                idle_by_class = ", ".join(
                    f"{self.params.gpu_classes[g]['name']}:{self.state.n_idle_per_class[g]:.0f}"
                    for g in range(self.params.G)
                )
                print(f"t={t:3d}: Power={power_t/1000:6.1f} kW, "
                      f"Idle=[{idle_by_class}], "
                      f"Busy={self.state.total_busy_gpus():5.0f}, "
                      f"States={len(self.state.get_all_states())}")
        
        print()
        print("Simulation complete!")

        # ── Job arrival / miss summary (F3 enhanced) ─────────────────────
        missed          = self.dynamics.total_jobs_missed
        missed_by_mu    = self.dynamics.missed_by_mu
        missed_by_type  = self.dynamics.missed_by_type
        admitted        = self.dynamics.total_jobs_admitted
        completed       = self.dynamics.total_jobs_completed
        print()
        print("=" * 60)
        print("JOB SUMMARY  (F3 + F5)")
        print("=" * 60)
        print(f"  Total arrived      : {self.total_jobs_arrived:,.0f}")
        print(f"  Total admitted     : {admitted:,.0f}")
        print(f"  Total completed    : {completed:,.0f}")
        print(f"  Total missed       : {missed:,.0f}", end="")
        if self.total_jobs_arrived > 0:
            print(f"  ({100 * missed / self.total_jobs_arrived:.1f}%)")
        else:
            print()
        print()
        if missed > 0:
            print("  F3 — Miss breakdown by memory class:")
            for mu in sorted(missed_by_mu.keys()):
                pct_of_missed = 100 * missed_by_mu[mu] / missed
                pct_of_total  = 100 * missed_by_mu[mu] / max(self.total_jobs_arrived, 1)
                print(f"    µ={mu:>3d} GB : {missed_by_mu[mu]:>8,.0f}  "
                      f"({pct_of_missed:.1f}% of missed, {pct_of_total:.1f}% of arrived)")
            print()
            print("  F3 — Miss breakdown by job type:")
            for jtype in ['prefill', 'decode', 'fine_tuning', 'training']:
                count = missed_by_type.get(jtype, 0.0)
                pct_of_missed = 100 * count / missed if missed > 0 else 0.0
                pct_of_total  = 100 * count / max(self.total_jobs_arrived, 1)
                print(f"    {jtype:<12}: {count:>8,.0f}  "
                      f"({pct_of_missed:.1f}% of missed, {pct_of_total:.1f}% of arrived)")
        print()
        print("  F5 — Conservation check summary:")
        if self.conservation_violations == 0:
            print("    All checks PASSED (0 violations)")
        else:
            print(f"    WARNING: {self.conservation_violations} violation(s) detected "
                  f"— see [F5 VIOLATION] lines above")
        print("=" * 60)
        
    def plot_results(self):
        """Plot the simulation results"""
        
        fig, axes = plt.subplots(3, 1, figsize=(12, 10))
        
        # Plot 1: Power consumption
        ax = axes[0]
        ax.plot(self.history['time'], 
                [p/1000 for p in self.history['power']], 
                label='Actual Power', linewidth=2)
        if self.params.sinusoidal:
            t_vals  = self.history['time']
            pt_vals = [pt/1000 for pt in self.history['p_target']]
            ax.plot(t_vals, pt_vals, 'r--', linewidth=2,
                    label=f'Target (sinusoidal {self.params.P_target_base/1000:.0f}'
                          f'+/-{self.params.P_target_amplitude/1000:.0f} kW)')
        else:
            ax.axhline(self.params.P_target_base/1000, color='r', linestyle='--',
                       label=f'Target ({self.params.P_target_base/1000:.0f} kW)',
                       linewidth=2)
        ax.set_ylabel('Power (kW)', fontsize=12)
        ax.set_title('Power Consumption Over Time', fontsize=14, fontweight='bold')
        ax.legend(fontsize=10)
        ax.grid(True, alpha=0.3)
        
        # Plot 2: GPU utilization
        ax = axes[1]
        ax.plot(self.history['time'], self.history['n_idle'], 
                label='Idle GPUs', linewidth=2)
        ax.plot(self.history['time'], self.history['n_busy'], 
                label='Busy GPUs', linewidth=2)
        ax.axhline(self.params.N_gpus, 
                   color='k', linestyle='--', alpha=0.5,
                   label=f'Total ({self.params.N_gpus})')
        ax.set_ylabel('Number of GPUs', fontsize=12)
        ax.set_title('GPU Utilization', fontsize=14, fontweight='bold')
        ax.legend(fontsize=10)
        ax.grid(True, alpha=0.3)
        
        #Waiting Queue
        ax = axes[2]
        ax.plot(self.history['time'], self.history['waiting_queue'], 
            linewidth=2, color='orange')
        ax.set_ylabel('Jobs Waiting', fontsize=12)
        ax.set_title('Waiting Queue Size', fontsize=14, fontweight='bold')
        ax.grid(True, alpha=0.3)
        ax.fill_between(self.history['time'], 0, self.history['waiting_queue'], 
                     alpha=0.3, color='orange')
        
        plt.tight_layout()
        import os
        profile  = 'sinusoidal' if self.params.sinusoidal else 'flat'
        lam_str  = f"{self.params.lambda_arrival:.0f}"
        fname    = f'simulation_results_LP_{profile}_lambda_{lam_str}.png'
        out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), fname)
        plt.savefig(out_path, dpi=150, bbox_inches='tight')
        print(f"Plot saved to {out_path}")
        
        return fig



    def save_run_metrics(self):
        """
        Save a JSON summary of this run keyed by lambda value.
        File: metrics_lambda_{lambda}.json in same directory as script.
        plot_section3() reads all such files to build the Section 3 figure.
        """
        import json, os
        import numpy as np

        lam   = self.params.lambda_arrival
        power = self.history['power']
        queue = self.history['waiting_queue']
        busy  = self.history['n_busy']
        missed         = self.dynamics.total_jobs_missed
        arrived        = self.total_jobs_arrived
        missed_by_type = dict(self.dynamics.missed_by_type)
        missed_by_mu   = {str(k): v for k, v in self.dynamics.missed_by_mu.items()}

        # Per-class mean busy GPUs
        # n_idle_per_class[t][g] -> mean idle per class -> busy = N_g - idle
        # Compute mean busy per class directly from per-class idle history
        # busy_g = N_g - idle_g  (only valid now that idle is correctly tracked)
        idle_arr = np.array(self.history['n_idle_per_class'])  # shape (T, G)
        mean_busy_per_class = {}
        for g, gc in enumerate(self.params.gpu_classes):
            mean_idle_g = float(np.mean(idle_arr[:, g]))
            mean_busy_g = float(gc['n_gpus'] - mean_idle_g)
            mean_busy_per_class[gc['name']] = mean_busy_g

        targets = self.history['p_target']
        rms_kw  = float(np.sqrt(np.mean(
                      [(p - pt)**2 for p, pt in zip(power, targets)]
                  )) / 1000)
        q_arr = np.array(queue)
        q_pp  = float(q_arr.max() - q_arr.min()) if len(q_arr) > 0 else 0.0

        metrics = {
            'lambda':            lam,
            'sinusoidal':        self.params.sinusoidal,
            'miss_rate':         float(missed / max(arrived, 1)),
            'rms_error_kw':      rms_kw,
            'queue_pp':          q_pp,
            'mean_queue':        float(np.mean(queue)),
            'mean_busy_total':   float(np.mean(busy)),
            'mean_busy_per_class': mean_busy_per_class,
            'total_arrived':     int(arrived),
            'total_missed':      float(missed),
            'missed_by_type':    missed_by_type,
            'missed_by_mu':      missed_by_mu,
            'avg_power_kw':      float(np.mean(power) / 1000),
            'P_target_kw':       float(self.params.P_target / 1000),
        }

        script_dir = os.path.dirname(os.path.abspath(__file__))
        fname = os.path.join(script_dir, f'metrics_lambda_{lam:.1f}.json')
        with open(fname, 'w') as f:
            json.dump(metrics, f, indent=2)
        print(f"Metrics saved -> {fname}")
        return fname


# ============================================================================
# SECTION 3 PLOTTER
# reads all metrics_lambda_*.json files in a folder and produces the
# 5-panel figure that report1 §3 asks for.
# ============================================================================

def compute_lambda_star(params):
    """Back-of-envelope lam* from report1 §1."""
    E_tau    = np.mean([jt['tau_r_mean'] for jt in params.job_types.values()])
    P_idle   = params.get_power(0)
    P_max    = params.get_power(params.K - 1)
    N_active = (params.P_target - params.N_gpus * P_idle) / (P_max - P_idle)
    lam_star = N_active / E_tau
    return lam_star, E_tau, N_active


def plot_section3(folder=None):
 
    
    import json, glob, os
    import numpy as np
    import matplotlib.pyplot as plt

    if folder is None:
        folder = os.path.dirname(os.path.abspath(__file__))

    # Load all metric files
    pattern = os.path.join(folder, 'metrics_lambda_*.json')
    files   = sorted(glob.glob(pattern))
    if not files:
        print(f"No metrics files found in {folder}")
        print("Run the simulation at several lam values first - each run saves a JSON file.")
        return

    data = []
    for fp in files:
        with open(fp) as f:
            data.append(json.load(f))
    data.sort(key=lambda x: x['lambda'])

    lambdas       = [d['lambda']        for d in data]
    miss_rates    = [d['miss_rate']     for d in data]
    rms_errors    = [d['rms_error_kw']  for d in data]
    mean_queues   = [d['mean_queue']    for d in data]

    # Analytical lam* - use reference params
    ref_params = GPUSystemParameters()
    lam_star, E_tau, N_active = compute_lambda_star(ref_params)
    miss_pred = [max(0.0, 1.0 - lam_star / lam) for lam in lambdas]

    # Per-class busy GPUs
    class_names = [gc['name'] for gc in ref_params.gpu_classes]
    class_colors = ['tab:blue', 'tab:orange', 'tab:red']
    busy_by_class = {name: [] for name in class_names}
    for d in data:
        for name in class_names:
            busy_by_class[name].append(d['mean_busy_per_class'].get(name, 0.0))

    # Per-type miss rates
    type_names   = ['prefill', 'decode', 'fine_tuning', 'training']
    type_colors  = ['tab:green', 'tab:blue', 'tab:orange', 'tab:red']
    miss_by_type = {jt: [] for jt in type_names}
    for d in data:
        arr = max(d['total_arrived'], 1)
        for jt in type_names:
            miss_by_type[jt].append(d['missed_by_type'].get(jt, 0.0) / arr)

    # ── Build figure ─────────────────────────────────────────────────────────
    fig, axes = plt.subplots(3, 2, figsize=(16, 14))
    fig.suptitle(
        f"Section 3 - lambda-Sweep Results  |  Flat Target {ref_params.P_target/1000:.0f} kW  |  "
        "F1 fix: prefill tau_r=2, tau_s=1\n"
        f"lam* ≈ {lam_star:.1f} jobs/slot  (N_active={N_active:.0f}, E[tau]={E_tau:.2f})",
        fontsize=13, fontweight='bold'
    )
    kw = dict(marker='o', linewidth=2, markersize=7)

    # Panel 1 - Miss rate
    ax = axes[0, 0]
    ax.plot(lambdas, miss_rates, color='crimson', label='Empirical miss rate', **kw)
    ax.plot(lambdas, miss_pred,  color='black', linestyle='--', linewidth=2,
            label=f'Analytical: max(0, 1-lam*/lam)\nlam*={lam_star:.1f}')
    ax.axvline(lam_star, color='navy', linestyle=':', linewidth=1.5,
               label=f'lam* = {lam_star:.1f}')
    ax.set_xlabel('Arrival rate lambda (jobs/slot)', fontsize=11)
    ax.set_ylabel('Miss rate', fontsize=11)
    ax.set_title('1. Miss Rate vs lam', fontsize=12, fontweight='bold')
    ax.set_ylim(-0.02, 1.02)
    ax.legend(fontsize=9); ax.grid(True, alpha=0.3)

    # Panel 2 - RMS tracking error
    ax = axes[0, 1]
    ax.plot(lambdas, rms_errors, color='steelblue', label='RMS tracking error', **kw)
    ax.axvline(lam_star, color='navy', linestyle=':', linewidth=1.5,
               label=f'lam* = {lam_star:.1f}')
    ax.set_xlabel('Arrival rate lambda (jobs/slot)', fontsize=11)
    ax.set_ylabel('RMS error (kW)', fontsize=11)
    ax.set_title('2. RMS Tracking Error vs lam', fontsize=12, fontweight='bold')
    ax.legend(fontsize=9); ax.grid(True, alpha=0.3)

    # Panel 3 - Mean queue length
    ax = axes[1, 0]
    ax.plot(lambdas, mean_queues, color='darkorange', label='Mean waiting queue', **kw)
    ax.axvline(lam_star, color='navy', linestyle=':', linewidth=1.5,
               label=f'lam* = {lam_star:.1f}')
    ax.set_xlabel('Arrival rate lambda (jobs/slot)', fontsize=11)
    ax.set_ylabel('Mean jobs waiting', fontsize=11)
    ax.set_title('3. Mean Queue Length vs lam', fontsize=12, fontweight='bold')
    ax.legend(fontsize=9); ax.grid(True, alpha=0.3)

    # Panel 4 - Busy GPUs by memory class
    ax = axes[1, 1]
    for name, col in zip(class_names, class_colors):
        ax.plot(lambdas, busy_by_class[name], color=col,
                label=f'{name} busy', **kw)
    ax.axhline(N_active, color='black', linestyle='--', linewidth=1.5,
               label=f'N_active* = {N_active:.0f}')
    ax.axvline(lam_star, color='navy', linestyle=':', linewidth=1.5,
               label=f'lam* = {lam_star:.1f}')
    ax.set_xlabel('Arrival rate lambda (jobs/slot)', fontsize=11)
    ax.set_ylabel('Mean busy GPUs', fontsize=11)
    ax.set_title('4. GPU Utilisation vs lam (by memory class)', fontsize=12, fontweight='bold')
    ax.legend(fontsize=9); ax.grid(True, alpha=0.3)

    # Panel 5 - Miss rate by job type
    ax = axes[2, 0]
    for jt, col in zip(type_names, type_colors):
        ax.plot(lambdas, miss_by_type[jt], color=col, label=jt, **kw)
    ax.axvline(lam_star, color='navy', linestyle=':', linewidth=1.5,
               label=f'lam* = {lam_star:.1f}')
    ax.set_xlabel('Arrival rate lambda (jobs/slot)', fontsize=11)
    ax.set_ylabel('Miss rate by job type', fontsize=11)
    ax.set_title('5. Miss Rate by Job Type vs lam', fontsize=12, fontweight='bold')
    ax.legend(fontsize=9); ax.grid(True, alpha=0.3)

    # Panel 6 - Summary table
    ax = axes[2, 1]
    ax.axis('off')
    col_labels = ['lam', 'Miss %', 'RMS kW', 'Avg Queue', 'Avg Power kW']
    rows = []
    for d in data:
        rows.append([
            f"{d['lambda']:.0f}",
            f"{d['miss_rate']*100:.1f}%",
            f"{d['rms_error_kw']:.1f}",
            f"{d['mean_queue']:.0f}",
            f"{d['avg_power_kw']:.1f}",
        ])
    tbl = ax.table(cellText=rows, colLabels=col_labels,
                   loc='center', cellLoc='center')
    tbl.auto_set_font_size(False)
    tbl.set_fontsize(10)
    tbl.scale(1, 1.5)
    ax.set_title('Summary Table', fontsize=12, fontweight='bold')

    plt.tight_layout()
    out = os.path.join(folder, 'section3_sweep.png')
    plt.savefig(out, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"Section 3 figure saved -> {out}")
    print(f"  Data points: lam = {lambdas}")
    print(f"  Analytical lam* = {lam_star:.2f}")
    return out



# ============================================================================
# SECTION 4: TRANSITION MATRIX A AND ANALYTICAL LAMBDA*
# ============================================================================
#
# Report1 §4: Build the population transition matrix A per GPU class.
# A is substochastic: column sums <= 1 (deficit = job completion probability).
# Stability condition: rho(A_g) < 1 for all classes g.
#
# For the heterogeneous fleet, A is block-diagonal — one block per class.
# The binding constraint is the class with the smallest lambda*_g.
#
# Per-class job assignment (cheapest-fit policy):
#   A16: prefill only (mu=16 fits A16; decode/ft/training all bypass A16)
#   A40: decode + fine_tuning (mu=40; training bypasses to A80)
#   A80: training only (mu=80; A80 is the exclusive class for training)
#
# Note: in the simulation, prefill/decode/ft can also spill into higher
# classes when their primary class is full, but for the analytical matrix
# we use the primary assignment to keep blocks independent. This gives
# a conservative (lower) lambda*_g per class.
#
# Frequency policy: uniform split across active levels k=1,2,3,4
# (u_k = 0.25 each) as first-pass approximation per report1 §4.
# ============================================================================

def build_transition_matrix(params):
    """
    Build the block-diagonal transition matrix A for the heterogeneous fleet.

    Returns a dict with per-class spectral radii, per-class lambda*,
    the system lambda*, and the analytical mean busy GPU prediction.

    Parameters
    ----------
    params : GPUSystemParameters

    Returns
    -------
    dict with keys:
        rho          : {class_name: rho(A_g)}
        lambda_star  : {class_name: lambda*_g}
        lambda_star_system : float  (min across classes = binding constraint)
        lambda_min_system  : float  (arrival rate needed to reach P_target)
        N_busy_pred  : callable(lam) -> predicted mean busy GPUs at arrival rate lam
        class_results: detailed per-class data
    """
    import numpy as np
    from scipy.sparse import lil_matrix, csc_matrix
    from scipy.sparse.linalg import eigs
    from scipy.sparse.linalg import spsolve

    # ── Quantization grid ────────────────────────────────────────────────────
    Q = 4  # grid step = 1/Q slots
    # Active frequency levels and rates (exclude k=0 idle)
    K_active = [k for k in range(1, params.K)]
    rates    = [params.get_rate(k) for k in K_active]
    n_K      = len(K_active)
    u_k      = 1.0 / n_K   # uniform split

    # ── Per-class job type assignment ─────────────────────────────────────────
    # For each class, which job types are primarily assigned there?
    # We use the primary (cheapest-fit) class for each job type.
    class_job_types = {
        'A16': ['prefill'],                    # mu=16, cheapest fit
        'A40': ['decode', 'fine_tuning'],      # mu=40, cheapest fit
        'A80': ['training'],                   # mu=80, A80 only
    }

    results = {}

    for g, gc in enumerate(params.gpu_classes):
        class_name = gc['name']
        job_names  = class_job_types[class_name]

        # ── State space for this class ────────────────────────────────────────
        # States: (tau, s) on 1/Q grid
        # tau in [1/Q, tau_max],  s in [0, s_max]
        tau_vals = [i / Q for i in range(1, params.tau_max * Q + 1)]
        s_vals   = [i / Q for i in range(0, params.s_max   * Q + 1)]

        states    = []
        state_idx = {}
        for tau in tau_vals:
            for s in s_vals:
                state_idx[(round(tau*Q), round(s*Q))] = len(states)
                states.append((tau, s))
        d = len(states)

        # ── Build A_g ─────────────────────────────────────────────────────────
        A = lil_matrix((d, d), dtype=np.float64)

        for i, (tau, s) in enumerate(states):
            for r_k in rates:
                tau_next = tau - r_k
                s_next   = s   - (1 - r_k)

                if tau_next <= 0:
                    continue   # job completes — substochastic defect

                tn_key = round(tau_next * Q)
                sn_key = round(max(0.0, s_next) * Q)

                if (tn_key, sn_key) in state_idx:
                    j      = state_idx[(tn_key, sn_key)]
                    A[j, i] += u_k

        A_csc = csc_matrix(A)

        # ── Spectral radius rho(A_g) ──────────────────────────────────────────
        try:
            vals, _ = eigs(A_csc, k=1, which='LM', maxiter=5000, tol=1e-6)
            rho = float(np.abs(vals[0]))
        except Exception:
            # Power iteration fallback
            v   = np.ones(d) / d
            rho = 1.0
            for _ in range(500):
                v2   = A_csc @ v
                norm = np.linalg.norm(v2)
                if norm < 1e-14:
                    break
                rho = norm
                v   = v2 / norm

        # ── Initial state distribution p_g for this class ─────────────────────
        # p[i] = probability a single arrival to this class starts in state i.
        # Report1 §4: p is the joint pmf of (tau_r, tau_s) for a single arrival,
        # averaged over job types assigned to this class.
        # Geometric(p) is integer-valued: tau_r in {1,2,...}, tau_s in {0,1,...}.
        # Integers map exactly onto the 1/Q grid since Q=4 and all values are
        # whole numbers — so no quantization error in p.
        p = np.zeros(d)
        for jt_name in job_names:
            jt   = params.job_types[jt_name]
            tr_p = jt['tau_r_p']   # = 1 / tau_r_mean
            ts_p = jt['tau_s_p']   # = 1 / tau_s_mean

            for tau_int in range(1, params.tau_max + 1):
                prob_tau = (1 - tr_p) ** (tau_int - 1) * tr_p
                if prob_tau < 1e-10:
                    break
                key_tau = round(tau_int * Q)   # exact on integer grid

                for s_int in range(0, params.s_max + 1):
                    prob_s = (1 - ts_p) ** s_int * ts_p
                    if prob_s < 1e-10:
                        break
                    key_s = round(s_int * Q)   # exact on integer grid

                    key = (key_tau, key_s)
                    if key in state_idx:
                        p[state_idx[key]] += prob_tau * prob_s / len(job_names)

        p_sum = p.sum()
        if p_sum > 0:
            p /= p_sum

        # ── Mean busy GPUs: N_busy(lam) = lam * 1^T (I-A)^{-1} p ─────────────
        # Solve (I - A)^T x = 1  =>  x = (I - A^T)^{-1} 1
        # Then N_busy = lam * x^T p
        I_minus_A = csc_matrix(
            (np.ones(d), (np.arange(d), np.arange(d))), shape=(d, d)
        ) - A_csc

        try:
            ones = np.ones(d)
            x    = spsolve(I_minus_A.T, ones)
            mean_service_time = float(x @ p)   # E[busy slots per arrival]
        except Exception:
            # If matrix is singular (rho >= 1), service time is infinite
            mean_service_time = float('inf')

        # ── Lambda*_g: capacity bound for this class ──────────────────────────
        # lambda*_g (per-class rate) = N_g / mean_service_time
        # lambda*_g_total (total arrival rate) = lambda*_g / arrival_fraction_g
        #
        # arrival_fraction_g = fraction of total arrivals routed to this class
        # = len(job_names) / total_job_types  (uniform split across types)
        N_g = gc['n_gpus']
        total_job_types   = len(params.job_types)
        arrival_fraction  = len(job_names) / total_job_types  # e.g. 0.25 for A80 (1/4 types)

        if mean_service_time > 0 and not np.isinf(mean_service_time):
            lam_star_g       = N_g / mean_service_time          # per-class rate
            lam_star_g_total = lam_star_g / arrival_fraction    # total arrival rate
        else:
            lam_star_g       = 0.0
            lam_star_g_total = 0.0

        # ── Lambda_min_g: arrival rate to fill this class to P_target share ───
        # Power allocated to class g proportionally: P_target * N_g / N_gpus
        P_target_g   = params.P_target * (N_g / params.N_gpus)
        P_idle_g     = params.get_power(0) * N_g
        P_active_g   = P_target_g - P_idle_g
        # Average power per busy GPU (at uniform frequency mix)
        avg_power_busy = np.mean([params.get_power(k) for k in K_active])
        P_per_busy   = avg_power_busy - params.get_power(0)
        N_needed_g   = P_active_g / P_per_busy if P_per_busy > 0 else 0.0
        lam_min_g    = N_needed_g / mean_service_time                        if mean_service_time > 0 and not np.isinf(mean_service_time)                        else float('inf')

        lam_min_g_total = lam_min_g / arrival_fraction if lam_min_g < float('inf') else float('inf')

        results[class_name] = {
            'rho':               rho,
            'lambda_star':       lam_star_g,        # per-class arrival rate
            'lambda_star_total': lam_star_g_total,  # total arrival rate (scaled)
            'lambda_min':        lam_min_g,          # per-class
            'lambda_min_total':  lam_min_g_total,    # total arrival rate (scaled)
            'arrival_fraction':  arrival_fraction,
            'mean_service_time': mean_service_time,
            'N_g':               N_g,
            'job_types':         job_names,
            'p':                 p,
            'A_csc':             A_csc,
            'states':            states,
        }

        print(f"  [{class_name}] rho(A)={rho:.4f}  "
              f"E[svc]={mean_service_time:.2f}  "
              f"arr_frac={arrival_fraction:.2f}  "
              f"lam*_class={lam_star_g:.2f}  "
              f"lam*_total={lam_star_g_total:.2f}  "
              f"jobs={job_names}")

    # ── System-level bounds (in terms of TOTAL arrival rate) ─────────────────
    # Binding class = class with smallest lam*_total
    lam_star_system = min(r['lambda_star_total'] for r in results.values()
                          if r['lambda_star_total'] > 0)
    lam_min_system  = max(r['lambda_min_total']  for r in results.values()
                          if not np.isinf(r['lambda_min_total']))
    binding_class   = min(results.items(),
                          key=lambda x: x[1]['lambda_star_total']
                          if x[1]['lambda_star_total'] > 0 else float('inf'))[0]

    # ── N_busy prediction across all classes ─────────────────────────────────
    # lam here is TOTAL arrival rate; per-class rate = lam * arrival_fraction_g
    def N_busy_pred(lam):
        total = 0.0
        for cr in results.values():
            mst  = cr['mean_service_time']
            N_g  = cr['N_g']
            frac = cr['arrival_fraction']
            lam_g = lam * frac   # per-class arrival rate
            if np.isinf(mst):
                total += N_g
            else:
                total += min(lam_g * mst, N_g)
        return total

    return {
        'rho':                  {name: r['rho']               for name, r in results.items()},
        'lambda_star':          {name: r['lambda_star']        for name, r in results.items()},
        'lambda_star_total':    {name: r['lambda_star_total']  for name, r in results.items()},
        'lambda_min_total':     {name: r['lambda_min_total']   for name, r in results.items()},
        'lambda_star_system':   lam_star_system,
        'lambda_min_system':    lam_min_system,
        'binding_class':        binding_class,
        'N_busy_pred':        N_busy_pred,
        'class_results':      results,
    }


def print_transition_matrix_summary(tm):
    """Pretty-print the transition matrix analysis results."""
    print()
    print("=" * 75)
    print("SECTION 4 — TRANSITION MATRIX ANALYSIS")
    print("=" * 75)
    print(f"{'Class':<8} {'rho(A)':>8} {'E[svc]':>8} {'arr_frac':>9} "
          f"{'lam*_class':>11} {'lam*_total':>11} {'Jobs'}")
    print("-" * 75)
    for name in tm['class_results']:
        r = tm['class_results'][name]
        print(f"  {name:<6} {r['rho']:>8.4f} {r['mean_service_time']:>8.2f} "
              f"{r['arrival_fraction']:>9.2f} "
              f"{r['lambda_star']:>11.2f} "
              f"{r['lambda_star_total']:>11.2f}  "
              f"{r['job_types']}")
    print("-" * 75)
    print(f"  Binding class               = {tm['binding_class']} "
          f"(smallest lam*_total)")
    print(f"  System lambda_max (total)   = {tm['lambda_star_system']:.2f} jobs/slot")
    print(f"  System lambda_min (total)   = {tm['lambda_min_system']:.2f} jobs/slot")
    window = tm['lambda_star_system'] - tm['lambda_min_system']
    if window > 0:
        print(f"  Bilateral control window    = [{tm['lambda_min_system']:.2f}, "
              f"{tm['lambda_star_system']:.2f}]  (width={window:.2f})")
    else:
        print(f"  Bilateral control window    = EMPTY "
              f"(lambda_min={tm['lambda_min_system']:.2f} > "
              f"lambda_max={tm['lambda_star_system']:.2f})")
        print("  => No operating point achieves bounded queue AND full P_target tracking.")
        print("     This motivates the MPC formulation and infinite-pool variant.")
    print("=" * 75)



def plot_section4(tm, sweep_folder=None):
    """
    Generate the two-panel key plot from report1 §4.

    Panel 1 (left):  Miss rate vs lambda
        - Empirical curve from sweep JSON files (if available)
        - Analytical prediction: max(0, 1 - lambda*_total / lambda)
        - Vertical line at lambda*_total (binding class)

    Panel 2 (right): Mean busy GPUs vs lambda
        - Simulation average from sweep JSON files (if available)
        - Analytical N_busy(lambda) from transition matrix Eq.(5)
        - Analytical curve diverges at lambda*; simulation saturates

    Parameters
    ----------
    tm          : dict returned by build_transition_matrix()
    sweep_folder: folder containing metrics_lambda_*.json files
                  (defaults to same folder as this script)
    """
    import os, glob, json
    import numpy as np
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt

    if sweep_folder is None:
        sweep_folder = os.path.dirname(os.path.abspath(__file__))

    lam_star  = tm['lambda_star_system']
    lam_min   = tm['lambda_min_system']
    N_busy_fn = tm['N_busy_pred']
    binding   = tm['binding_class']

    # ── Load empirical sweep data if available ────────────────────────────────
    files = sorted(glob.glob(os.path.join(sweep_folder, 'metrics_lambda_*.json')))
    emp_lam, emp_miss, emp_busy = [], [], []
    for fp in files:
        with open(fp) as f:
            d = json.load(f)
        emp_lam.append(d['lambda'])
        emp_miss.append(d['miss_rate'])
        emp_busy.append(d['mean_busy_total'])

    # ── Analytical curves over dense lambda range ─────────────────────────────
    lam_dense    = np.linspace(1, max(max(emp_lam) if emp_lam else 60, 65), 300)
    miss_analytic = [max(0.0, 1.0 - lam_star / lam) for lam in lam_dense]
    busy_analytic = [N_busy_fn(lam) for lam in lam_dense]

    # Per-class N_busy for panel 2 detail
    class_colors = {'A16': 'tab:blue', 'A40': 'tab:orange', 'A80': 'tab:red'}

    # ── Figure ────────────────────────────────────────────────────────────────
    fig, axes = plt.subplots(1, 2, figsize=(16, 6))
    fig.suptitle(
        f"Section 4 Key Plot — Transition Matrix vs Simulation\n"
        f"Binding class: {binding}  |  "
        f"lam*_total = {lam_star:.1f} jobs/slot  |  "
        f"lam_min = {lam_min:.1f} jobs/slot",
        fontsize=13, fontweight='bold'
    )

    # ── Panel 1: Miss rate ────────────────────────────────────────────────────
    ax = axes[0]
    ax.plot(lam_dense, miss_analytic, 'k--', linewidth=2,
            label=f'Analytical: max(0, 1-lam*/lam)\nlam*={lam_star:.1f} (binding: {binding})')
    if emp_lam:
        ax.plot(emp_lam, emp_miss, 'o-', color='crimson', linewidth=2,
                markersize=8, label='Empirical miss rate (simulation)')
    ax.axvline(lam_star, color='navy', linestyle=':', linewidth=2,
               label=f'lam*_total = {lam_star:.1f}')
    if lam_min < lam_star:
        ax.axvline(lam_min, color='green', linestyle=':', linewidth=2,
                   label=f'lam_min = {lam_min:.1f}')
        ax.axvspan(lam_min, lam_star, alpha=0.08, color='green',
                   label='Bilateral control window')

    ax.set_xlabel('Total arrival rate lambda (jobs/slot)', fontsize=12)
    ax.set_ylabel('Miss rate', fontsize=12)
    ax.set_title('Panel 1: Miss Rate vs lambda', fontsize=12, fontweight='bold')
    ax.set_ylim(-0.02, 1.02)
    ax.legend(fontsize=9)
    ax.grid(True, alpha=0.3)

    # Annotation
    ax.annotate(
        f'Analytical and empirical\nlam* should align here',
        xy=(lam_star, 0.05), xytext=(lam_star + 5, 0.25),
        arrowprops=dict(arrowstyle='->', color='navy'),
        fontsize=9, color='navy'
    )

    # ── Panel 2: Mean busy GPUs ───────────────────────────────────────────────
    ax = axes[1]
    ax.plot(lam_dense, busy_analytic, 'k--', linewidth=2,
            label=f'Analytical N_busy(lam) — diverges at lam*={lam_star:.1f}')

    # Per-class analytical curves
    for name, cr in tm['class_results'].items():
        mst  = cr['mean_service_time']
        N_g  = cr['N_g']
        frac = cr['arrival_fraction']
        col  = class_colors.get(name, 'gray')
        busy_g = [min(lam * frac * mst, N_g) for lam in lam_dense]
        ax.plot(lam_dense, busy_g, color=col, linestyle='-.', linewidth=1.5,
                alpha=0.7, label=f'{name} analytical (N_g={N_g})')

    if emp_lam:
        ax.plot(emp_lam, emp_busy, 's-', color='steelblue', linewidth=2,
                markersize=8, label='Empirical mean busy GPUs (simulation)')

    total_N = sum(cr['N_g'] for cr in tm['class_results'].values())
    ax.axhline(total_N, color='black', linestyle='--', linewidth=1,
               alpha=0.5, label=f'N_total = {total_N}')
    ax.axvline(lam_star, color='navy', linestyle=':', linewidth=2,
               label=f'lam*_total = {lam_star:.1f}')

    ax.set_xlabel('Total arrival rate lambda (jobs/slot)', fontsize=12)
    ax.set_ylabel('Mean busy GPUs', fontsize=12)
    ax.set_title('Panel 2: Mean Busy GPUs vs lambda\n'
                 '(analytical diverges at lam*; simulation saturates)',
                 fontsize=12, fontweight='bold')
    ax.legend(fontsize=9)
    ax.grid(True, alpha=0.3)

    plt.tight_layout()
    out = os.path.join(sweep_folder, 'section4_key_plot.png')
    plt.savefig(out, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"Section 4 key plot saved -> {out}")

    if emp_lam:
        print(f"  Empirical lambda values plotted: {emp_lam}")
        # Check alignment
        closest_idx = min(range(len(emp_lam)),
                          key=lambda i: abs(emp_lam[i] - lam_star))
        emp_miss_at_star = emp_miss[closest_idx]
        analytic_at_star = max(0.0, 1.0 - lam_star / emp_lam[closest_idx])
        print(f"  At lambda~={emp_lam[closest_idx]}: "
              f"empirical miss={emp_miss_at_star*100:.1f}%  "
              f"analytical={analytic_at_star*100:.1f}%")
        if abs(emp_miss_at_star - analytic_at_star) < 0.05:
            print("  => GOOD AGREEMENT: population model correctly predicts boundary.")
        else:
            print("  => GAP DETECTED: check per-class arrival fraction scaling.")
    return out

# ============================================================================
# STEP 8: RUN IT!
# ============================================================================

if __name__ == "__main__":
    params = GPUSystemParameters()

    # ── Profile switch ────────────────────────────────────────────────────
    # To run sinusoidal profile, uncomment:
    # params.sinusoidal = True
    # To change lambda, uncomment and edit:
    # params.lambda_arrival = 25.0

    # ── Section 4: Transition matrix (analytical, no simulation needed) ──
    print("Building transition matrix (Section 4)...")
    tm = build_transition_matrix(params)
    print_transition_matrix_summary(tm)
    plot_section4(tm)   # saves section4_key_plot.png

    sim = GPUSimulator(params)
    sim.run()

    # Time-series plot for this run
    sim.plot_results()

    # Save metrics JSON for Section 3 sweep figure
    sim.save_run_metrics()

    # ── To build the Section 3 figure after running several lam values: ────
    # Uncomment the line below once you have metrics files for multiple lams.
    # plot_section3()  # reads all metrics_lambda_*.json in the script folder
    
    # Print summary statistics
    print("\n" + "="*60)
    print("SUMMARY STATISTICS")
    print("="*60)
    
    avg_power = np.mean(sim.history['power'])
    std_power = np.std(sim.history['power'])
    max_power = np.max(sim.history['power'])
    min_power = np.min(sim.history['power'])
    
    print(f"Average power:  {avg_power/1000:.2f} kW")
    print(f"Std dev:        {std_power/1000:.2f} kW")
    print(f"Max power:      {max_power/1000:.2f} kW")
    print(f"Min power:      {min_power/1000:.2f} kW")
    print(f"Target:         {params.P_target/1000:.2f} kW")
    print(f"Deviation:      {abs(avg_power - params.P_target)/1000:.2f} kW")
    
    avg_util = np.mean(sim.history['n_busy']) / params.N_gpus * 100
    print(f"\nAverage GPU utilization: {avg_util:.1f}%")
    print(f"Average idle GPUs: {np.mean(sim.history['n_idle']):.0f}")